### ISSUE TITLE
Update unicodeWords along with lodash

### ISSUE THREAD

**Issue by toastal** [purescript-contrib/purescript-strings-extra#10]
When I originally wrote this I just ported the `words` [code from lodash](https://github.com/lodash/lodash/commits/master/.internal/unicodeWords.js) as it was battle-tested. Given it's had some updates/bugfixes, this should too to follow in step. I may have a look this weekend.

Also one of those code blocks got changed from `purescript` to `pures`. I spell it `purse` a lot on accident :joy:

**Comment by thomashoneyman** [comment]
Whoops — I was probably trying to type ‘purs’ 😬
